[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm = "7HhA6WBHpugdJGm8svXpDtUsfWR87G5Vt7XihJAjc6MT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
